[install]
linker = "isolated"

[test]
preload = ["./packages/react/test-setup.ts"]
coverage = true
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = ["**/dist/**", "**/node_modules/**", "**/test/**", "**/test-setup.ts"]
