name: QA
on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Audit, Lint & Format
    runs-on: ubuntu-slim

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Audit dependencies
        run: bun audit --audit-level=high
      - name: Lint & Format
        run: bun run lint

  build:
    name: Build & Test
    needs: lint
    runs-on: ubuntu-slim
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build packages
        run: bun run build
      - name: Run tests
        run: bun test
        env:
          ZEROX_API_KEY: ${{ secrets.ZEROX_API_KEY }}
          ANKR_API_KEY: ${{ secrets.ANKR_API_KEY }}

